/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ChessCore.GUI;

import ChessCore.ChessGame;
import ChessCore.Move;
import ChessCore.PawnPromotion;
import ChessCore.Pieces.Pawn;
import static ChessCore.Player.WHITE;
import ChessCore.Square;

/**
 *
 * @author DELL
 */
public class ListOfPromotedPiecces extends javax.swing.JFrame {

    private ChessGame game;
    private BoardPanel Drawedboard;
    private Square from;
    private Square to;
    private PieceImage selectedPiece;

    public ListOfPromotedPiecces(ChessGame game, BoardPanel Drawedboard, Square from, Square to, PieceImage selectedPiece) {
        initComponents();
        this.game = game;
        this.Drawedboard = Drawedboard;
        this.selectedPiece = selectedPiece;
        this.from = from;
        this.to = to;
    }

    public void PromoteTo(PawnPromotion pawnPromotion, int row, int col) {
        Move move = new Move.MoveBuilder(from, to)
                .setPawnPromotion(pawnPromotion)
                .build();
        PromotedPieceFactory promotedPieceFactory = new PromotedPieceFactory();
        PieceImage promotedPiece = promotedPieceFactory.createPromotedPiece(game, row, col, pawnPromotion);
        if (game.makeMove(move)) {
            if (game.getWhoseTurn().equals(WHITE)) {
                Drawedboard.removePieceAtSquare(7 - row, 7 - col);
            } else {
                Drawedboard.removePieceAtSquare(row, col);
            }
            Drawedboard.removePiece(selectedPiece);
            selectedPiece = null;
            Drawedboard.addPieceAtSquare(promotedPiece);
            Drawedboard.flipBoard();
            Drawedboard.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KnightButton = new javax.swing.JButton();
        RookButton = new javax.swing.JButton();
        BishopButton = new javax.swing.JButton();
        QueenButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        KnightButton.setText("Knight");
        KnightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KnightButtonActionPerformed(evt);
            }
        });

        RookButton.setText("Rook");
        RookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RookButtonActionPerformed(evt);
            }
        });

        BishopButton.setText("Bishop");
        BishopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BishopButtonActionPerformed(evt);
            }
        });

        QueenButton.setText("Queen");
        QueenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KnightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BishopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QueenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(RookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(KnightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BishopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(QueenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RookButtonActionPerformed
        PromoteTo(PawnPromotion.Rook, to.getRank().getValue(), to.getFile().getValue());
        this.setVisible(false);
    }//GEN-LAST:event_RookButtonActionPerformed

    private void KnightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnightButtonActionPerformed
        PromoteTo(PawnPromotion.Knight, to.getRank().getValue(), to.getFile().getValue());
        this.setVisible(false);
    }//GEN-LAST:event_KnightButtonActionPerformed

    private void QueenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueenButtonActionPerformed
        PromoteTo(PawnPromotion.Queen, to.getRank().getValue(), to.getFile().getValue());
        this.setVisible(false);
    }//GEN-LAST:event_QueenButtonActionPerformed

    private void BishopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BishopButtonActionPerformed
        PromoteTo(PawnPromotion.Bishop, to.getRank().getValue(), to.getFile().getValue());
        this.setVisible(false);
    }//GEN-LAST:event_BishopButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
 /*    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListOfPromotedPiecces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListOfPromotedPiecces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListOfPromotedPiecces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListOfPromotedPiecces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /*  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListOfPromotedPiecces(row,col).setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BishopButton;
    private javax.swing.JButton KnightButton;
    private javax.swing.JButton QueenButton;
    private javax.swing.JButton RookButton;
    // End of variables declaration//GEN-END:variables
}
